apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bookswap-backend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "512Mi"
        run.googleapis.com/cpu: "1000m"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/bookswap-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: bookswap-secrets
              key: DATABASE_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: bookswap-secrets
              key: SECRET_KEY
        - name: GOOGLE_BOOKS_API_KEY
          valueFrom:
            secretKeyRef:
              name: bookswap-secrets
              key: GOOGLE_BOOKS_API_KEY
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
